---
driver:
  name: vagrant
  provision: true

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[cspp-test::default]
    attributes:
