---
driver:
  name: vagrant
  provision: true

provisioner:
  name: chef_zero
  
verifier:
  name: inspec

platforms:
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[cspp::default]
    attributes:
